### ISSUE TITLE
Math.random should be seeded with world seed

### ISSUE THREAD

**Issue by detolly** [CaioFPeres/SkyChunksAndSkyIslands#2]

**Comment by CaioFPeres** [comment]
I think i got what you meant, but i dont think that is necessary.
Because independently of the seed, the plugin will "roll a dice" to see if it will delete the chunk or not, there is where Math.random is applied. And this "dice" does not have any weight, so you dont have a relation of probability with the seed.
What i mean is that, if the seed is different in any way, it will not make it easier or harder to decide if the chunk will be deleted or not. 
It would make a difference only if there was a seed that deletes a lot of chunks, but as far as i know that is not possible because the world seed only changes how the world will be generated, so this already comprehends that the world will be generated regardless, as well as the chunks.
