### ISSUE TITLE
Remained chunks do not allign with minecraft chunk grid

### ISSUE THREAD

**Issue by Te4nick** [CaioFPeres/SkyChunksAndSkyIslands#3]
You should see this issue on a distance from spawn

**Comment by CaioFPeres** [comment]
Yes, both of the issues you created is about something i could not solve. I put an observation in readme.md about this.
If i change the code to delete an entire 16x16 chunk, it will crash, and i dont know why lol.

You can see here:

`chunk.getWorld().getBlockAt((chunk.getX() * 15) + i, h, (chunk.getZ() * 15) + j).setType(AIR);`

That i get the chunk coordinates ( which is given in chunk grid format (first chunk, second chunk and so on)) and then i multiply the chunk for 15 instead of 16. By doing that you will get the actual world coordinates, but it will start deleting a little before the actual chunk. And this keeps getting escalated.
If you change for 16, it will crash, dont know why. In theory it should work and be deleting the actual chunk, but it crashes or freezes. You can check for yourself. I guess multiplying by 15 is a little "hack". This problem doesn't impact on anything tho. If you discover how to fix this, let me know.

And about the issue you deleted where you talked about the thread, that is a clever idea, to delete half of the chunk instead of assigning the whole chunk to a thread based on percentage. But, after i did that thread thing i realized by searching on the internet that minecraft server is only single threaded. So i dont know exactly what that runnable is doing, but if you compare with it or without, it doesn't have much difference (thats why i described on the update as "slight improvement", because it gave less errors lol). Maybe all it does is schedule in a queue, dont know for sure.

**Comment by Te4nick** [comment]
i've found a problem in max height that you delete. 128 is not the hightest naturally generated block, it's actually 150 [here](https://feedback.minecraft.net/hc/en-us/community/posts/360009407571-The-world-generation-and-Height-Limit) and [here](https://ibb.co/S05yWr2) is the image

**Comment by CaioFPeres** [comment]
Yes, that's right. I left 128 because of the nether and usually is hard to see mountains that high, and elevating the height of the deletion will increase a lot the processing required to delete them. It may seem little difference from 128 to 150 but its for every chunk, so it sums up a lot.
But i will see if the server can stand up to 150 height. From my previous tests, it was not handling well more than 128. But i did some small improvements i guess, then i'll try again.
I didnt know 150 was the highest naturally generated block tho, thanks :)

**Comment by Te4nick** [comment]
I think that the realization is wrong. Minecraft is struggling generating its own chunks, but plugin forces it to delete them on generation. This causes a lot of issues. Maybe instead some kind of mod should only generate this 1% of chunks?

**Comment by CaioFPeres** [comment]
Yes, thats right, but as far as i studied the API (bukkit/spigot/paper), to be able to generate a specific world, you need to specify all the parameters of the world generation. Basically, you need to set the parameters Minecraft Default World Generation uses. Thats a lot of work and very hard. I couldn't find a way to just disable the generation of the chunk, while it uses the default generation... Because, as you may know, the default Minecraft API is not fully accessible since it is in java bytecode.
Mod or plugin really does the same thing, i choose to create a plugin because it could be used online, but if a mod provides a functionality of disabling the generation of a chunk or such, while using the default generation, in a way that makes the process easier, i could use it. 
But i didn't go too far into mods because i thought it would use the same procedures as third-party servers APIs ( not being able to disable the generation of the chunk while uses the default Minecraft world generation).
If you discover how to do it tho, let me know.
